"use client";

import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { appointmentService } from "@/services/appointmentService";
import { pharmacyService } from "@/services/pharmacyService";
import { patientService } from "@/services/patientService";
import { PrintSheet } from "@/components/layout/print-sheet";
import { date, dateTime } from "@/lib/format";

const FREQ_TEXT: Record<string, string> = {
  "1-0-0": "Morning",
  "0-1-0": "Afternoon",
  "0-0-1": "Night",
  "1-0-1": "Morning and night",
  "1-1-1": "Morning, afternoon and night",
  "1-1-1-1": "Four times a day",
  "0-0-0-1": "At bedtime",
  Q6H: "Every 6 hours",
  Q8H: "Every 8 hours",
  SOS: "When required",
  STAT: "Immediately, once",
  Weekly: "Once a week",
};

export default function PrescriptionPrint() {
  const { id } = useParams<{ id: string }>();
  const rx = useQuery({ queryKey: ["prescription", id], queryFn: () => pharmacyService.getPrescription(id) });
  const patient = useQuery({ queryKey: ["patient", rx.data?.patientId], queryFn: () => patientService.getById(rx.data!.patientId), enabled: Boolean(rx.data) });
  const appt = useQuery({ queryKey: ["appointment", rx.data?.encounterId], queryFn: () => appointmentService.getById(rx.data!.encounterId!), enabled: Boolean(rx.data?.encounterId && rx.data.source === "OPD") });
  if (!rx.data || !patient.data) return <p className="p-8 text-center text-sm text-muted-foreground">{rx.error ? "Prescription not found." : "Preparing prescription…"}</p>;
  const r = rx.data;
  const p = patient.data;
  const c = appt.data?.consultation;
  return (
    <PrintSheet title="Prescription" meta={<>{r.rxNo} · {dateTime(r.createdAt)}</>}>
      <section className="grid grid-cols-2 gap-x-8 gap-y-1 rounded border border-neutral-300 p-3 text-[11.5px]">
        <p><b>Patient:</b> {p.fullName}</p>
        <p><b>UHID:</b> {p.uhid}</p>
        <p><b>Age / sex:</b> {p.ageLabel} / {p.gender}</p>
        <p><b>Mobile:</b> {p.phone}</p>
        <p><b>Allergies:</b> {p.allergies.map((a) => a.substance).join(", ") || "None known"}</p>
        <p><b>ABHA:</b> {p.abhaNumber ?? "Not linked"}</p>
        {appt.data?.vitals && (
          <p className="col-span-2"><b>Vitals:</b> BP {appt.data.vitals.bpSystolic}/{appt.data.vitals.bpDiastolic} mmHg · Pulse {appt.data.vitals.pulse}/min · SpO₂ {appt.data.vitals.spo2}% · Temp {appt.data.vitals.tempF} °F{appt.data.vitals.weightKg ? ` · Wt ${appt.data.vitals.weightKg} kg` : ""}</p>
        )}
      </section>
      {c?.chiefComplaint && <p className="mt-3"><b>Complaints:</b> {c.chiefComplaint}</p>}
      <p className="mt-1"><b>Diagnosis:</b> {c?.diagnoses.map((d) => `${d.name} (${d.code})`).join("; ") || r.diagnosis}</p>
      <p className="mt-4 text-2xl font-serif leading-none">℞</p>
      <table className="mt-2 w-full border-collapse text-[11.5px]">
        <thead>
          <tr className="border-b border-neutral-400 text-left">
            <th className="py-1.5 pr-2">#</th>
            <th className="py-1.5 pr-2">Medicine</th>
            <th className="py-1.5 pr-2">Dose</th>
            <th className="py-1.5 pr-2">When</th>
            <th className="py-1.5 pr-2">Duration</th>
            <th className="py-1.5 pr-2">Instructions</th>
            <th className="py-1.5 text-right">Qty</th>
          </tr>
        </thead>
        <tbody>
          {r.items.map((it, i) => (
            <tr key={it.id} className="border-b border-neutral-200 align-top">
              <td className="py-1.5 pr-2">{i + 1}</td>
              <td className="py-1.5 pr-2"><b>{it.drug.brand}</b> {it.drug.strength}<br /><span className="text-neutral-600">{it.drug.generic}</span></td>
              <td className="py-1.5 pr-2">{it.dose} {it.route !== "Oral" ? `(${it.route})` : ""}</td>
              <td className="py-1.5 pr-2">{it.frequency}<br /><span className="text-neutral-600">{FREQ_TEXT[it.frequency] ?? ""}</span></td>
              <td className="py-1.5 pr-2">{it.durationDays} days</td>
              <td className="py-1.5 pr-2">{it.instructions}</td>
              <td className="py-1.5 text-right">{it.qty}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {c?.labOrderIds.length ? <p className="mt-3"><b>Investigations ordered:</b> see lab requisition</p> : null}
      {c?.advice && <p className="mt-3"><b>Advice:</b> {c.advice}</p>}
      {c?.followUpOn && <p className="mt-1"><b>Review on:</b> {date(c.followUpOn, "EEEE, d MMMM yyyy")} (book at the front desk or on the MediCore app)</p>}
      <div className="mt-12 flex items-end justify-between">
        <p className="text-[10px] text-neutral-500">Generated by MediCore HMS. Valid for dispensing at any pharmacy in India. Schedule H/H1 drugs dispensed only against this prescription.</p>
        <div className="text-right">
          <div className="mb-1 h-10 w-44 border-b border-neutral-500" />
          <p className="font-semibold">{r.doctor.name}</p>
          <p className="text-[11px] text-neutral-600">{r.doctor.departmentName}</p>
        </div>
      </div>
    </PrintSheet>
  );
}
