"use client";

import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ipdService } from "@/services/ipdService";
import { patientService } from "@/services/patientService";
import { PrintSheet } from "@/components/layout/print-sheet";
import { date, dateTime } from "@/lib/format";

export default function DischargePrint() {
  const { id } = useParams<{ id: string }>();
  const a = useQuery({ queryKey: ["admission", id], queryFn: () => ipdService.getAdmission(id) });
  const p = useQuery({ queryKey: ["patient", a.data?.patientId], queryFn: () => patientService.getById(a.data!.patientId), enabled: Boolean(a.data) });
  if (!a.data || !p.data) return <p className="p-8 text-center text-sm text-muted-foreground">{a.error ? "Admission not found." : "Preparing summary…"}</p>;
  const adm = a.data;
  const s = adm.dischargeSummary;
  if (!s) return <p className="p-8 text-center text-sm text-muted-foreground">No discharge summary has been saved for this admission.</p>;
  const pt = p.data;
  return (
    <PrintSheet title="Discharge summary" meta={<>{adm.ipNo} · {s.status === "Final" ? "Final" : "Draft, not for release"}</>}>
      <section className="grid grid-cols-2 gap-x-8 gap-y-1 rounded border border-neutral-300 p-3 text-[11.5px]">
        <p><b>Patient:</b> {pt.fullName}</p>
        <p><b>UHID:</b> {pt.uhid}</p>
        <p><b>Age / sex:</b> {pt.ageLabel} / {pt.gender}</p>
        <p><b>ABHA:</b> {pt.abhaNumber ?? "Not linked"}</p>
        <p><b>Admitted:</b> {dateTime(adm.admittedAt)}</p>
        <p><b>Discharged:</b> {adm.dischargedAt ? dateTime(adm.dischargedAt) : "Planned"}</p>
        <p><b>Consultant:</b> {adm.doctor.name}, {adm.doctor.departmentName}</p>
        <p><b>Ward / bed:</b> {adm.ward.name}, {adm.bed.code}</p>
        <p className="col-span-2"><b>Allergies:</b> {pt.allergies.map((x) => `${x.substance} (${x.reaction})`).join(", ") || "None known"}</p>
      </section>
      <h2 className="mt-4 font-semibold">Final diagnosis</h2>
      <ul className="list-disc pl-5">{s.finalDiagnoses.map((d) => <li key={d.code}>{d.name} ({d.code})</li>)}</ul>
      <h2 className="mt-3 font-semibold">Reason for admission</h2>
      <p>{adm.reason}</p>
      <h2 className="mt-3 font-semibold">Hospital course</h2>
      <p className="whitespace-pre-line">{s.hospitalCourse}</p>
      {s.proceduresDone.length > 0 && (<><h2 className="mt-3 font-semibold">Procedures</h2><ul className="list-disc pl-5">{s.proceduresDone.map((x) => <li key={x}>{x}</li>)}</ul></>)}
      <p className="mt-3"><b>Condition at discharge:</b> {s.conditionAtDischarge}</p>
      {s.dischargeMedications.length > 0 && (
        <>
          <h2 className="mt-3 font-semibold">Medications on discharge</h2>
          <table className="mt-1 w-full border-collapse text-[11.5px]">
            <thead><tr className="border-b border-neutral-400 text-left"><th className="py-1 pr-2">Medicine</th><th className="py-1 pr-2">Dose</th><th className="py-1 pr-2">Frequency</th><th className="py-1">Duration</th></tr></thead>
            <tbody>{s.dischargeMedications.map((m, i) => <tr key={i} className="border-b border-neutral-200"><td className="py-1 pr-2">{m.drug}</td><td className="py-1 pr-2">{m.dose}</td><td className="py-1 pr-2">{m.frequency}</td><td className="py-1">{m.duration}</td></tr>)}</tbody>
          </table>
        </>
      )}
      <h2 className="mt-3 font-semibold">Follow-up</h2>
      <p>{s.followUp}</p>
      {s.instructions.length > 0 && (<><h2 className="mt-3 font-semibold">Instructions</h2><ul className="list-disc pl-5">{s.instructions.map((x) => <li key={x}>{x}</li>)}</ul></>)}
      <p className="mt-3 text-[11px]">In an emergency, call {"+91 80 4718 2211"} or come to the Emergency Department (24x7).</p>
      <div className="mt-10 flex items-end justify-between">
        <p className="text-[10px] text-neutral-500">Prepared {date(s.preparedAt, "d MMM yyyy, HH:mm")} by {s.preparedBy}. Generated by MediCore HMS.</p>
        <div className="text-right"><div className="mb-1 h-10 w-44 border-b border-neutral-500" /><p className="font-semibold">{adm.doctor.name}</p><p className="text-[11px] text-neutral-600">Treating consultant</p></div>
      </div>
    </PrintSheet>
  );
}
