"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "motion/react";
import { Check, Info, Pencil, RotateCw, Sparkles, X } from "lucide-react";
import type { AiMeta, AiStream, RiskScore } from "@/types";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { StatusBadge } from "@/components/feedback/status-badge";
import { ICON_STROKE } from "@/lib/constants";
import { ago } from "@/lib/format";
import { cn } from "@/lib/utils";

/* ---------- Disclaimer & confidence ---------- */

export function AiDisclaimer({ className }: { className?: string }) {
  return (
    <Tooltip>
      <TooltipTrigger
        render={
          <span
            tabIndex={0}
            className={cn("inline-flex h-5 items-center gap-1 rounded-full bg-info-soft px-2 text-[11px] font-medium whitespace-nowrap text-info-fg focus-visible:outline-2", className)}
          />
        }
      >
        <Sparkles className="size-3" strokeWidth={2} aria-hidden />
        AI suggestion · Requires clinician review
      </TooltipTrigger>
      <TooltipContent className="max-w-64">Generated by a model from the patient record. It can be wrong or incomplete and never replaces clinical judgement.</TooltipContent>
    </Tooltip>
  );
}

export function confidenceLabel(c: number): "High" | "Moderate" | "Low" {
  return c >= 0.85 ? "High" : c >= 0.7 ? "Moderate" : "Low";
}

/** Meter: accent fill on a lighter step of the same hue (dataviz meter spec). */
export function ConfidenceMeter({ value, className }: { value: number; className?: string }) {
  const pct = Math.round(value * 100);
  const label = confidenceLabel(value);
  return (
    <div className={cn("flex items-center gap-2 text-xs", className)}>
      <span className="text-muted-foreground">Confidence</span>
      <span role="meter" aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct} aria-label={`Model confidence ${pct}%`} className="relative h-1.5 w-16 overflow-hidden rounded-full bg-info-soft">
        <span className={cn("absolute inset-y-0 left-0 rounded-full", label === "Low" ? "bg-warning" : "bg-info")} style={{ width: `${pct}%` }} />
      </span>
      <span className="font-medium tabular">
        {pct}% <span className="font-normal text-muted-foreground">{label.toLowerCase()}</span>
      </span>
    </div>
  );
}

/* ---------- Markdown-lite rendering for streamed text ---------- */

function inline(text: string): React.ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*)/g).map((part, i) => (part.startsWith("**") && part.endsWith("**") ? <strong key={i} className="font-semibold">{part.slice(2, -2)}</strong> : part));
}

export function MarkdownLite({ text, streaming }: { text: string; streaming?: boolean }) {
  const blocks: React.ReactNode[] = [];
  const lines = text.split("\n");
  let list: string[] = [];
  const flush = (key: string) => {
    if (list.length) {
      blocks.push(
        <ul key={key} className="space-y-1 pl-4">
          {list.map((l, i) => (
            <li key={i} className="list-disc marker:text-subtle-foreground">
              {inline(l)}
            </li>
          ))}
        </ul>,
      );
      list = [];
    }
  };
  lines.forEach((line, i) => {
    if (line.startsWith("- ")) {
      list.push(line.slice(2));
      return;
    }
    flush(`l${i}`);
    if (line.startsWith("## ")) blocks.push(<h3 key={i} className="pt-2 text-xs font-semibold tracking-wide text-muted-foreground first:pt-0">{line.slice(3)}</h3>);
    else if (line.trim()) blocks.push(<p key={i}>{inline(line)}</p>);
  });
  flush("end");
  return (
    <div className="space-y-2 text-sm leading-relaxed">
      {blocks}
      {streaming && <span aria-hidden className="inline-block h-4 w-1.5 translate-y-0.5 animate-pulse rounded-sm bg-info" />}
    </div>
  );
}

/* ---------- Streaming hook ---------- */

type Phase = "idle" | "analyzing" | "streaming" | "done" | "error";

export function useAiStream(start: (signal: AbortSignal) => Promise<AiStream>) {
  const [phase, setPhase] = useState<Phase>("idle");
  const [text, setText] = useState("");
  const [meta, setMeta] = useState<AiMeta>();
  const [error, setError] = useState<unknown>();
  const ctrl = useRef<AbortController | undefined>(undefined);

  const run = useCallback(async () => {
    ctrl.current?.abort();
    const c = new AbortController();
    ctrl.current = c;
    setPhase("analyzing");
    setText("");
    setError(undefined);
    try {
      const res = await start(c.signal);
      if (c.signal.aborted) return;
      setMeta(res.meta);
      setPhase("streaming");
      let acc = "";
      for await (const chunk of res.stream) {
        if (c.signal.aborted) return;
        acc += chunk;
        setText(acc);
      }
      setPhase("done");
    } catch (e) {
      if (!c.signal.aborted) {
        setError(e);
        setPhase("error");
      }
    }
  }, [start]);

  useEffect(() => () => ctrl.current?.abort(), []);
  const reset = () => {
    ctrl.current?.abort();
    setPhase("idle");
    setText("");
  };
  return { phase, text, meta, error, run, reset };
}

/* ---------- Analyzing state ---------- */

export function Analyzing({ steps, label = "Analyzing" }: { steps: string[]; label?: string }) {
  const [i, setI] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setI((x) => Math.min(steps.length - 1, x + 1)), 520);
    return () => clearInterval(t);
  }, [steps.length]);
  return (
    <div className="space-y-3 p-4" role="status" aria-live="polite">
      <div className="flex items-center gap-2 text-sm font-medium">
        <span className="relative flex size-2">
          <span className="absolute inline-flex size-full animate-ping rounded-full bg-info opacity-60 motion-reduce:hidden" />
          <span className="relative inline-flex size-2 rounded-full bg-info" />
        </span>
        {label}…
      </div>
      <ul className="space-y-1.5 text-xs text-muted-foreground">
        {steps.map((s, idx) => (
          <li key={s} className={cn("flex items-center gap-2 transition-opacity", idx > i && "opacity-35")}>
            {idx < i ? <Check className="size-3.5 text-stable" /> : <span className="size-3.5" aria-hidden />}
            {s}
          </li>
        ))}
      </ul>
      <div className="space-y-2 pt-1" aria-hidden>
        {[92, 78, 85].map((w) => (
          <div key={w} className="h-3 animate-pulse rounded bg-muted" style={{ width: `${w}%` }} />
        ))}
      </div>
    </div>
  );
}

/* ---------- Sources footer ---------- */

export function AiSources({ meta }: { meta: AiMeta }) {
  return (
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
      <span className="flex items-center gap-1">
        <Info className="size-3" aria-hidden /> Based on
      </span>
      {meta.sources.map((s) =>
        s.href ? (
          <Link key={s.label} href={s.href} className="underline decoration-border-strong underline-offset-2 hover:text-foreground">
            {s.label}
          </Link>
        ) : (
          <span key={s.label}>{s.label}</span>
        ),
      )}
      <span className="ml-auto">
        {meta.model} · {ago(meta.generatedAt)}
      </span>
    </div>
  );
}

/* ---------- Panel ---------- */

export type ReviewDecision = "accepted" | "edited" | "dismissed";

export function AiPanel({
  title,
  meta,
  children,
  actions,
  footer,
  className,
  onRegenerate,
  busy,
}: {
  title: string;
  meta?: AiMeta;
  children: React.ReactNode;
  actions?: React.ReactNode;
  footer?: React.ReactNode;
  className?: string;
  onRegenerate?: () => void;
  busy?: boolean;
}) {
  return (
    <section className={cn("flex min-w-0 flex-col overflow-hidden rounded-xl border border-info/25 bg-card", className)} aria-label={title}>
      <div className="flex flex-wrap items-center gap-2 border-b border-info/15 bg-info-soft/40 px-4 py-2.5">
        <Sparkles className="size-4 text-info" strokeWidth={ICON_STROKE} aria-hidden />
        <h2 className="mr-auto text-sm font-medium">{title}</h2>
        <AiDisclaimer />
        {actions}
        {onRegenerate && (
          <Button variant="ghost" size="icon-sm" onClick={onRegenerate} disabled={busy} aria-label="Regenerate">
            <RotateCw strokeWidth={ICON_STROKE} />
          </Button>
        )}
      </div>
      <div className="min-w-0 flex-1">{children}</div>
      {(meta || footer) && (
        <div className="space-y-2 border-t px-4 py-2.5">
          {meta && <ConfidenceMeter value={meta.confidence} />}
          {footer}
          {meta && <AiSources meta={meta} />}
        </div>
      )}
    </section>
  );
}

/** Explicit clinician review. AI output is never applied without it. */
export function ReviewBar({ onAccept, onEdit, onDismiss, decision, acceptLabel = "Accept" }: { onAccept?: () => void; onEdit?: () => void; onDismiss?: () => void; decision?: ReviewDecision; acceptLabel?: string }) {
  if (decision)
    return (
      <p className="flex items-center gap-1.5 text-xs text-muted-foreground" role="status">
        {decision === "dismissed" ? <X className="size-3.5" /> : <Check className="size-3.5 text-stable" />}
        {decision === "accepted" ? "Accepted by clinician" : decision === "edited" ? "Edited and accepted by clinician" : "Dismissed by clinician"}
      </p>
    );
  return (
    <div className="flex flex-wrap items-center gap-2">
      {onAccept && (
        <Button size="sm" onClick={onAccept}>
          <Check /> {acceptLabel}
        </Button>
      )}
      {onEdit && (
        <Button size="sm" variant="outline" onClick={onEdit}>
          <Pencil /> Edit before use
        </Button>
      )}
      {onDismiss && (
        <Button size="sm" variant="ghost" onClick={onDismiss}>
          Dismiss
        </Button>
      )}
    </div>
  );
}

/* ---------- Risk scores ---------- */

const LEVEL_TONE = { Low: "stable", Moderate: "warning", High: "critical", Critical: "critical" } as const;

export function RiskScoreCard({ score, compact = false }: { score: RiskScore; compact?: boolean }) {
  const [open, setOpen] = useState(!compact);
  const maxPts = Math.max(3, ...score.factors.map((f) => f.points));
  return (
    <div className="rounded-lg border bg-card">
      <button type="button" onClick={() => setOpen((v) => !v)} aria-expanded={open} className="flex w-full items-center gap-3 px-3 py-2.5 text-left">
        <div className="min-w-0 flex-1">
          <p className="truncate text-xs text-muted-foreground">{score.label}</p>
          <p className="flex items-baseline gap-2">
            <span className="text-xl font-semibold">{score.display}</span>
            <span className="text-[11px] text-muted-foreground">{score.scale}</span>
          </p>
        </div>
        <StatusBadge tone={LEVEL_TONE[score.level]}>{score.level}</StatusBadge>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden">
            <div className="space-y-3 border-t px-3 py-3">
              {score.factors.length ? (
                <ul className="space-y-1.5" aria-label="Contributing factors">
                  {score.factors.map((f) => (
                    <li key={f.label} className="grid grid-cols-[1fr_auto] items-center gap-x-3 text-xs">
                      <span className="truncate">
                        {f.label} <span className="text-muted-foreground">({f.value})</span>
                      </span>
                      <span className="flex items-center gap-1.5">
                        <span aria-hidden className="h-1.5 rounded-full bg-info" style={{ width: `${(f.points / maxPts) * 40}px` }} />
                        <span className="num w-6 text-right">+{f.points}</span>
                      </span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-muted-foreground">No contributing factors identified.</p>
              )}
              <p className="text-xs leading-relaxed">
                <span className="font-medium">Suggested response: </span>
                {score.recommendation}
              </p>
              <ConfidenceMeter value={score.meta.confidence} />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
